# Generated by Django 5.0.6 on 2024-06-07 09:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_flight_booking_time_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='booking_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
