# Generated by Django 5.0.6 on 2024-06-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_booking_is_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='req_seats',
            field=models.IntegerField(default=1),
        ),
    ]
