# Generated by Django 5.0.6 on 2024-06-12 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_booking_req_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='delay',
            field=models.DurationField(default=datetime.timedelta(seconds=5400)),
        ),
    ]
