# Generated by Django 5.0.6 on 2024-06-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_flight_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='delay',
            field=models.IntegerField(null=True),
        ),
    ]
